# Generated by Django 6.0.1 on 2026-06-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blrjobs',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='hydjobs',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='punejobs',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
